@echo off

echo Embutindo arquivos...

%GOPATH%\bin\go-bindata -prefix web/template -nomemcopy -nocompress -pkg templ -o assets/templ/templates.go web/template/...

%GOPATH%\bin\go-bindata -prefix web/html -nomemcopy -nocompress -pkg html -o assets/html/html.go web/html/...

%GOPATH%\bin\go-bindata -nomemcopy -nocompress -pkg assets -o assets/asset.go database/migrations/...